# BOF [O11o__10o_2o0]
# 思考エンジンのデフォルト値です。 CgfGoBan などの GUI はこのファイルを見ません

# Game - 対局１つ分に相当
[Game]

# Komi - コミ
Komi = 6.5

# BoardSize - 何路盤
BoardSize = 9

# MaxMoves - 最大手数
MaxMoves = 400

# BoardData - 盤面
#
# * '.' - 空点
# * 'x' - 黒石
# * 'o' - 白石
# * '+' - 枠
# * 半角空白は無視します
BoardData = '''
+ + + + + + + + + + +
+ . . . . . . . . . +
+ . . . . . . . . . +
+ . . . . . . . . . +
+ . . . . . . . . . +
+ . . . . . . . . . +
+ . . . . . . . . . +
+ . . . . . . . . . +
+ . . . . . . . . . +
+ . . . . . . . . . +
+ + + + + + + + + + +
'''

# PlayFirst - 先行。 black か white
PlayFirst = "black"

# ファイルやフォルダーのパスの設定
[Paths]

# PlainTextLog - コンソールのより詳細なログ
PlainTextLog = "kifuwarabe-uec17.log"

# JsonLog - コンピューター向けのログ
JsonLog = "kifuwarabe-uec17-json.log"

# EOF [O11o__10o_2o0]
